zero01101/openOutpaint

webui.bat

Making things a bit simpler for the initial launch :)

.bat file to launch python simple server for windows port 3456

---

css/index.css
index.html
js/settingsbar.js

preview ![](https://iloveur.mom/i/eqoJvq7nCi.gif)

New draggable settings panel

---

README.md
index.html

version bump and readfish

---

js/index.js

@zero01101 Just a commit to fix an issue on the last pull request (#14).
Sorry for any issues this may have caused.

fix scale factor slider broken by refactor

---

css/index.css
index.html
js/settingsbar.js

Had a thought of making a drag-able, re-sizeable div for the loaded image, need to figure out how to project the scaled img from it to the canvas somehow

make draggable class for possible future re-use

---

css/index.css
index.html
js/index.js

Checkerboard background to signal transparency

---

index.html
js/input.js
js/shortcuts.js
js/util.js

Some Keyboard Input support to input.js Allows configuration of shortcuts. Added shortcuts for undo/redo functionality.

Keyboard Input Support

---

css/index.css
index.html
js/commands.js
js/index.js
js/settingsbar.js
js/ui/history.js
js/util.js

History window things
Signed-off-by: Victor Seiji Hariki <victorseijih@gmail.com>

add history list view and interaction

---

README.md

From 28 to 5mb, also probably should just hyperlink all the files instead of having users download them with the project

Convert that large gif into 5mb webm embed

---

index.html
js/index.js

Switching models requires WebUI to be at least on commit [5a6387e189dc365c47a7979b9040d5b6fdd7ba43](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5a6387e189dc365c47a7979b9040d5b6fdd7ba43)
Updating the WebUI actually broke dreaming with this tool with the samplers hardcoded, so i added them from the api too. Make sure to test!
Also the model switching takes a while

Model switching, samplers from api

---

css/colors.css
css/ui/generic.css
index.html
js/index.js
js/input.js
js/settingsbar.js
js/ui/toolbar.js
js/util.js

This is a new pull request, with the same changes applied on #42, but now with 100% less messing with git trees.
This seems much more reasonable with my single commit, instead of the nearly two hundred that I was merging with the main branch from before.
-- same as previous pull request --
This pull request is for some changes in the mouse input code; mostly backward compatible, with minimal influence to the outside. But what is possible now is to create custom mouse listeners, with different button supports and allows for custom coordinate transformation. This is currently being used only for some infinity canvas tests on my side.
I also created a custom slider element to save some space in the interface. I was inspired quite a lot in Blender's value selectors, and created a slider that …

non-broken version on input-rework

---

js/settingsbar.js
js/ui/toolbar.js

Fixes #47  and makes rendering of slider a bit more flexible.

Img2img fix

---

css/index.css
js/index.js
js/ui/tool/select.js
js/ui/tool/stamp.js
js/util.js

Allows for selections and dreams to be sent to the resource manager, allows resource deselection when clicking on the currently selected item, put some extra comments and allow saving of a selected canvas area

Dream and Selection - Resource Manager Interaction and Selected Area saving

---

js/ui/tool/dream.js
js/ui/tool/maskbrush.js
js/ui/tool/select.js
js/ui/tool/stamp.js
js/util.js

Signed-off-by: Victor Seiji Hariki <victorseijih@gmail.com>
(cherry picked from commit 6299b561f196a7c78c66a8d21b2e1b27cecdee77)

some fixes and comments

---

css/index.css
index.html
js/index.js
js/input.js
js/settingsbar.js

Fixed scrolling on basically everything but the canvas, prompt fields
now automatically expand when focused, prompt, host and neg prompt now
are stored on local storage. On hover, prompt and neg prompt fields now
show full text in tooltips.
Last commit for today.

Quick patches 2

---

css/index.css
index.html
js/index.js

Detects if it is a CORS problem, checks for invalid saved host configuration, WebUI connection status indicator
Created this branch to test features for bugs and compatibility before merging into the main branch. Any features I think are okayish, I will be pushing to here.

improved network handling

---

js/ui/tool/dream.js

fixes overmask application before brush mask 

---

css/index.css
css/ui/tool/colorbrush.css
index.html
js/initalize/layers.populate.js
js/lib/input.js
js/ui/tool/colorbrush.js
res/icons/pipette.svg

Due to a breaking issue in chrome, will merge directly.
Signed-off-by: Victor Seiji Hariki <victorseijih@gmail.com>

fix chrome giant icon/add pipette tool (shift)

---

js/index.js
js/initalize/layers.populate.js
js/initalize/ui.populate.js
js/lib/ui.js
js/lib/util.js
js/ui/tool/colorbrush.js
js/ui/tool/dream.js
js/ui/tool/interrogate.js
js/ui/tool/maskbrush.js
js/ui/tool/select.js
js/ui/tool/stamp.js

Just some general fixes and an auto webui configuration checker to set img2img color correction and inpainting mask weight.

Some general fixes

---

index.html
js/index.js
js/ui/tool/dream.js

this was embarrassingly difficult because i'm unqualified lmao
i think i've probably done some Bad Things™ because of my use of `toolbar._current_tool` particularly, but like i literally had to spend a shameful amount of time walking back through how index.js generates sliders vs how dream.js calls toolbar to generate sliders and like HOW DO I ~~SHOT WEB~~ DO CALLBACK oh, that's how and just ... i'm not good at this lol

i think this should fix issue 90 - optional resolution/reticle sync

---

index.html
js/index.js
js/initalize/layers.populate.js
js/lib/input.d.js
js/lib/ui.js
js/lib/util.js
js/prompt.js
js/ui/tool/dream.js
js/ui/tool/generic.js
js/ui/tool/select.js

For now, changes default to sync cursor and resolution. Also adds generation resolution (albeit smaller) to cursor render to make it more explicit.

2022-12-13 Testing Pull

---

js/ui/tool/dream.js

An emergency fix for img2img masking (was very broken)

fix img2img mask canvas weirdness

---

js/ui/tool/dream.js

simple search/replace for keepMask[ed]
i think this grammatically makes a bit more sense, since we're keeping the unmasked areas as-is and altering the masked areas.  i only did a remedial search/replace over the project for `keepMask` (which included `keepMasked`) replacing it with `keepUnmask` - quick tests make it appear that nothing broke 🤞 but @seijihariki if i ruined things, please feel free to yell at me here :)

RFC- rename keepMask to keepUnmask

---

.gitignore
index.html
js/index.js
js/initalize/layers.populate.js
js/prompt.js
js/webui.js
pages/configuration.html

[Firefox Bug #733698](https://bugzilla.mozilla.org/show_bug.cgi?id=733698) Workaround for WebUI extension.
From gist https://gist.github.com/subzey/2030480.
Fixes manual dream selection required described on https://github.com/zero01101/openOutpaint-webUI-extension/issues/1

WebUI Extension Fixes

---

js/index.js

fixed fixed host

---

js/ui/tool/dream.js

at least this'll apparently do for now :)

adds preserve mask option

---

index.html
js/config.js
js/lib/input.js
js/ui/tool/dream.js
js/ui/tool/select.js

Relates to #116
Signed-off-by: Victor Seiji Hariki <victorseijih@gmail.com>

An easy fix for mouse wheel scrolling

---

css/layers.css
index.html
js/config.js
js/index.js
js/initalize/layers.populate.js
js/lib/input.js
js/ui/tool/colorbrush.js
js/ui/tool/dream.js
js/ui/tool/interrogate.js
js/ui/tool/maskbrush.js

Default overmask px now 20px as discussed in #125. This pull will also include inpainting model detection and offer to change on first boot, also from #125.
Will probably add tool settings persistence as well at some point. Not necessarily in this pull, but maybe the next.

Unused variable cleanup and new overmask px default

---

css/index.css
css/ui/generic.css
index.html
js/index.js
js/lib/toolbar.js
js/lib/ui.js
js/ui/tool/dream.js
pages/configuration.html

Model list now indicates if inpainting models.

Inpainting model indication color

---

index.html
js/index.js
pages/configuration.html

so i think this is pretty useful and i CHALLENGE ANYONE TO DISPROVE

more user configurable stuff

---

index.html
js/index.js
js/ui/tool/dream.js

not sure if useful or i'm just salty

return of HRfix lock px

---

index.html
js/global.js
js/index.js
js/ui/tool/dream.js

Compatibility fix with the old HRFix versions of the webui using the original openOutpaint HRFix implementation (firstphase_width = width / 2 and firstphase_height = height / 2).
Still displays alert on boot.

HRfix Compatibility

---

index.html
js/index.js

should fix https://github.com/zero01101/openOutpaint/issues/160

relax with the background checks especially if the tab isn't focused

---

css/index.css
css/ui/generic.css
index.html
js/index.js
js/lib/ui.js
pages/configuration.html
res/icons/refresh-cw.svg

so like i think that i'm doing this REALLY WRONG :( i tried replacing the contents of the autoselect with a [refreshed list of models](https://github.com/zero01101/openOutpaint/issues/167) but no matter what idiocy i applied, i ran into duplicated observers/handlers or truncated option lists until i manually cleared out the input field... i mean it when i say i'm kinda dumb lol :D  on that topic, this is also unpleasantly duplicated from the instantiation of the autoselect option element, but i tried to extract that into a repeatable function and that just ruined the context of the thing... plus the fact that i changed it from a `const` to a `let` so that may have inadvertently damaged something but i somewhat doubt that... 
ANYWAY please point and laugh and say "wtf are you even doing …

fixes issue 167?

---

index.html
js/ui/tool/select.js

Hi! I'm back!
Just a basic implementation of #223 
For now, only horizontal flip (we can add vertical flip too, but it would be redundant)

feat: Selection mirroring

---

js/index.js

Decode image before addResource in upscaleAndDownload, fixes loss of Resources after upscale, issue #293

Fix for issue #293
